image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:
  - java -jar ./artifacts/app-order.jar &
  - chmod +x gradlew
  - gradlew test -Dselenide.headless=true

build_script:

  - ./gradlew test --info
